### ISSUE TITLE
throws  "Cannot call method 'replace' of null"

### ISSUE THREAD

**Issue by grks** [sindresorhus/normalize-url#13]
There seems to be runtime error when using urls on format "protocol://host"

> n('custom://foo')
TypeError: Cannot call method 'replace' of null
    at module.exports (/test/node_modules/normalize-url/index.js:49:36)
    at repl:1:2
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.EventEmitter.emit (events.js:98:17)

Would expect it to manage to normalize this type of url or fail in a more controlled fashion?

**Comment by sindresorhus** [comment]
Yup, seems like an oversight. I don't have time to look into this right now, but PR welcome :)
