### ISSUE TITLE
Must use import to load  ES Module

### ISSUE THREAD

**Issue by Paulsonbigi** [sindresorhus/normalize-url#150]
{"message":"UNCAUGHTEXCEPTION: Error: Cannot find module 'normalize-url'\nRequire stack:\n- C:\\Users\\Paul\\Documents\\React-Projects\\MERN Ecommerce\\controllers\\auth.controllers.js\n- C:\\Users\\Paul\\Documents\\React-Projects\\MERN Ecommerce\\routes\\auth.routes.js\n- C:\\Users\\Paul\\Documents\\React-Projects\\MERN Ecommerce\\app.js\n- C:\\Users\\Paul\\Documents\\React-Projects\\MERN Ecommerce\\server.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:746:27)\n    at Module.require (internal/modules/cjs/loader.js:974:19)\n    at require (internal/modules/cjs/helpers.js:92:18)\n    at Object.<anonymous> (C:\\Users\\Paul\\Documents\\React-Projects\\MERN Ecommerce\\controllers\\auth.controllers.js:4:22)\n    
at Module._compile (internal/modules/cjs/loader.js:1085:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)\n    at Module.load (internal/modules/cjs/loader.js:950:32)\n    
at Function.Module._load (internal/modules/cjs/loader.js:790:14)\n    at Module.require (internal/modules/cjs/loader.js:974:19)\n    at require (internal/modules/cjs/helpers.js:92:18)\n    at Object.<anonymous> (C:\\Users\\Paul\\Documents\\React-Projects\\MERN Ecommerce\\routes\\auth.routes.js:4:26)\n    
at Module._compile (internal/modules/cjs/loader.js:1085:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)\n    at Module.load (internal/modules/cjs/loader.js:950:32)\n    
at Function.Module._load (internal/modules/cjs/loader.js:790:14)","level":"info"}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
